server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: validator-service

# CROSS ORIGIN
allowed:
  origins: http://localhost:8080, http://localhost:4200

# SWAGGER CONFIG
springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
